version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=rides_db
      - DB_HOST=db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend:/backend
    container_name: lb-rides-backend
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rides_db
    container_name: lb-rides-db
    restart: always